version: 2
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    working_directory: ~/repo
    branches:
      only:
        - master
    steps:
      - checkout
      - run: npm run docs:build
      - run: sh .circleci/push-gh-pages.sh .vuepress/dist
