version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'master' ]; then
              bash .circleci/deploy.sh
            fi
workflows:
  version: 2
  build:
    jobs:
      - deploy
